- defaults:
    link:
      relink: true
      create: true
      force: true
      glob: true


- clean: [ '~' ]

- link:
    ~/.zshrc: config/.zshrc
    ~/.gitconfig: config/git/.gitconfig
    ~/.config/starship/starship.toml: config/starship/starship.toml
    ~/.config/bat/bat.conf: config/bat/bat.conf
    ~/.config/atuin/config.toml: config/atuin/config.toml
    ~/.config/ghostty/config: config/ghostty/config
    ~/Library/Application Support/Code/User/settings.json: config/vscode/settings.json

- shell:
    - [ git submodule update --init --recursive, Installing submodules ]
